apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
spec:
  # list of containers
  containers:
  - name: debug
    image: chaitudocker5698/debug:v1
    command: ["sleep", "100000"] # it will be in sleep model for 1lac seconds so we can do operations