apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: # these labels are deployment labels
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: chaitudocker5698/mongodb:v1 # It will connect to docker hub and pull this image based on username
        imagePullPolicy: Always
--- # Below will provide communicatin to pod to pod, Since mongodb is not required to expose to outside world, we will go with clsuter-ip
apiVersion: v1
kind: Service 
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 #container-port